# Generated by Django 5.0.6 on 2024-06-13 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.TextField(default=datetime.date(2024, 6, 13))),
                ('expense_amount', models.FloatField()),
            ],
        ),
    ]
