# Generated by Django 5.0.6 on 2024-06-14 08:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.TextField(default=datetime.date(2024, 6, 14)),
        ),
    ]
