# Generated by Django 5.0.6 on 2024-06-14 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_expense_category_alter_expense_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date(2024, 6, 14)),
        ),
    ]
