# Generated by Django 5.0.6 on 2024-06-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
